services:
  zabbix-postgres:
    image: postgres:15-alpine
    container_name: zabbix_postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
    volumes:
      - zabbix_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zabbix -d zabbix"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-6.4-latest
    container_name: zabbix_server
    environment:
      DB_SERVER_HOST: zabbix-postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      ZBX_VALUECACHESIZE: 64M
      ZBX_CACHESIZE: 128M
      ZBX_TRENDCACHESIZE: 128M
    ports:
      - "10051:10051"
    depends_on:
      zabbix-postgres:
        condition: service_healthy
    networks:
      - zabbix-network
      - monitoring-network
    restart: unless-stopped

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-6.4-latest
    container_name: zabbix_web
    environment:
      DB_SERVER_HOST: zabbix-postgres
      DB_SERVER_PORT: 5432
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      ZBX_SERVER_HOST: zabbix-server
      ZBX_SERVER_PORT: 10051
      PHP_TZ: Europe/Moscow
    ports:
      - "8082:8080"
    depends_on:
      - zabbix-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - zabbix-network
    restart: unless-stopped

  zabbix-agent:
    image: zabbix/zabbix-agent2:alpine-6.4-latest
    container_name: zabbix_agent_fixed
    environment:
      ZBX_HOSTNAME: "postgresql-server"
      ZBX_SERVER_HOST: "zabbix-server"
      ZBX_SERVER: "zabbix-server"
      ZBX_SERVERACTIVE: "zabbix-server:10051"
      ZBX_TIMEOUT: 30
    depends_on:
      - zabbix-server
    networks:
      - zabbix-network
      - monitoring-network
    restart: unless-stopped

volumes:
  zabbix_postgres_data:

networks:
  zabbix-network:
    driver: bridge
  monitoring-network:
    external: true
