# pylint: disable=no-member
"""Add cascade delete from categories to questions.

Revision ID: 1ef649ed4eb1
Revises:
Create Date: 2025-09-08 03:06:44.910122

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ef649ed4eb1"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.alter_column("category_id", existing_type=sa.INTEGER(), nullable=False)
        # batch_op.drop_constraint(None, type_='foreignkey')  # noqa: ERA001
        batch_op.create_foreign_key(None, "categories", ["category_id"], ["id"], ondelete="CASCADE")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("questions", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")  # pyright: ignore[reportArgumentType]
        batch_op.create_foreign_key(None, "categories", ["category_id"], ["id"])
        batch_op.alter_column("category_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
