name: "Run Tests"
description: "Starts services, runs Pytest with Coverage and Allure, and uploads results"

inputs:
  codecov-token:
    description: "Codecov token for uploading reports"
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Python and UV
      uses: ./.github/actions/setup

    - name: Start services with Docker Compose
      run: docker compose up -d --build
      shell: bash

    - name: Wait for backend to be healthy
      run: |
        timeout 300 bash -c 'while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:8000/health)" != "200" ]]; do echo "Waiting for backend..."; sleep 5; done'
        echo "Backend is healthy!"
      shell: bash

    - name: Install Playwright Browsers inside container
      run: docker compose exec -T backend uv run playwright install --with-deps
      shell: bash

    - name: Run Pytest with Coverage inside Docker
      run: |
        docker compose exec -T backend uv run pytest \
          --rootdir /app \
          -v \
          --cov=backend \
          --cov-report=xml:/app/coverage-results/coverage.xml \
          --cov-report=html:/app/coverage-results/htmlcov \
          --alluredir=/app/allure-results \
          /app/tests
      shell: bash
      continue-on-error: true

    - name: Check Pytest exit code
      id: test-status
      run: |
        exit_code=$(docker compose exec -T backend echo $?)
        if [ $exit_code -ne 0 ]; then
          echo "Pytest failed with exit code $exit_code"
          exit 1
        fi
      shell: bash

    - name: Copy results from container
      if: always()
      run: |
        mkdir -p allure-results
        mkdir -p coverage-results
        docker compose cp backend:/app/allure-results/. ./allure-results/
        docker compose cp backend:/app/coverage-results/. ./coverage-results/
      shell: bash

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ inputs.codecov-token }}
        slug: ZhikharevAl/interview
        fail_ci_if_error: false

    - name: Store Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-results
        path: allure-results
        retention-days: 30

    - name: Store Coverage Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: coverage-results
        path: coverage-results
        retention-days: 30
